# Generated by Django 4.0.5 on 2022-06-18 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_neighborhood_posttype_profile_house_profile_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hood',
            new_name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbors', to='hood.neighborhood'),
        ),
    ]
