# Generated by Django 4.0.5 on 2022-06-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='neighborhood',
            new_name='hood',
        ),
    ]
