# Generated by Django 4.0.5 on 2022-06-19 09:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_rename_neighborhood_post_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bs_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
